######################################################################
# Automatically generated by qmake (2.01a) Paz May 27 18:00:47 2007
######################################################################

TEMPLATE = app
TARGET = QZinc
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h zincprocess.h
FORMS += f_qzinc.ui
SOURCES += main.cpp mainwindow.cpp zincprocess.cpp
RESOURCES += games.qrc
